name: Docker Image Test

on:
  push:
    branches: [ '**' ]
    paths: ['app/**','Dockerfile','.github/workflows/github-action-demo.yml']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-web-helloworld:0.0.1

    - name: Run Containerized App
      run: docker run -d  go-web-helloworld:0.0.1

    - name: Get HTTP response from the App
      run: curl -I http://127.0.0.1
